version: '3'
services:
  front:
    build: front/.
    ports:
      - "8080:80"
  # Proxy container which handles passing request to the actual services
  #    the container to which request is passed is chosen with the first part of request url
  #    for example: "http://localhost:8080/first/page" is proxied to "http://first:80/page"
  proxy:
    # image to start, image must be available in docker hub or built locally
    image: reap/proxy-for-docker-containers
    ports:
     - "9090:8080"
  lunch:
    build: backend/golang-lunch/.
  abc:
    build: backend/abc/.
    ports:
      - "8500:80"
  antell:
    build: backend/antell/.
  boardgames:
    build: backend/boardgame-club-connector
  now-listening:
    build: backend/now-listening/.
  rss:
    build: backend/rss/.
  turkuun:
    build: backend/turkuun/.
  deadline:
    build: backend/deadline_counter/.
    environment:
     - EVENTNAME=Star Wars Last Jedi premier
     - DEADLINE=2017-12-13 14:00 UTC
     